### ISSUE TITLE
Only inline styles are supported?

### ISSUE THREAD

**Issue by AndreyLuzinov** [adobe/react-webcomponent#22]
AFAIU this solution will work with shadow-dom only in case of inline styles?

**Comment by AndreyLuzinov** [comment]
I think it should be an optional parameter to pass styles or link ref into webcomponent while creation.

**Comment by alexmirea** [comment]
Hi @AndreyLuzinov. Currently we support only rendering the component in the shadow root. So if you want to add styles only inline styles on the element will work.

You are right, we don't support yet `<style/>`  or a link ref, for that we need to pass extra parameters here https://github.com/adobe/react-webcomponent/blob/master/lib/WebComponent.js#L142.

Could you please open a separate issue detailing the problem more formally, and we can discuss what the best solution would be.
