### ISSUE TITLE
Infinite loop with Redux and @byChildrenRefArray

### ISSUE THREAD

**Issue by Sc0rpic0m** [adobe/react-webcomponent#6]
I am not sure if we are already aware of this, 

But using the annotation byChildrenRefArray in combination with Redux seems to trigger an infinite loop.

The only thing needed to reproduce this is putting an @byChildrenRefArray in a DOM Model that will be used to initialize a controller that uses Redux <Provider>.

1) My question is, are we aware of this 
2) Can this be reproduced by using our internal projects or should I provide a sophisticated example?

Thanks !

**Comment by alexmirea** [comment]
Hi Niek!
Thanks for bringing this up, so far we are not aware of such issues, as far as I know it has we have used redux with the library not sure exactly if this decorator.

Could you please explain a bit more the usecase - if you cannot put the internal one maybe steps to reproduce it, Redux does a lot of things and I am not sure where the loop would be. So it you could point to a example would be great!

Thanks!

**Comment by Sc0rpic0m** [comment]
Seems to be fixed now right? I think we can close it.
